// ===== Publications Data =====
// Auto-generated from data/publications.csv — do not edit directly.
// Run: python scripts/build-data.py
const PUBLICATIONS = [
  // ── 2026 ──
  { title:"On Fairness of Task Arithmetic: The Role of Task Vectors", authors:["Laura Gomezjurado Gonzalez","Hiroki Naganuma","Kotaro Yoshida","Takafumi Horie","Yuji Naraki","Ryotaro Shimizu"], venue:"ICLR", year:2026, date:"May 2026", type:"conference", citations:0, links:{paper:"https://openreview.net/forum?id=LN1kzPFqJl"} },
  { title:"DisTaC: Conditioning Task Vectors via Distillation for Robust Model Merging", authors:["Kotaro Yoshida","Yuji Naraki","Takafumi Horie","Ryotaro Shimizu","Ioannis Mitliagkas","Hiroki Naganuma"], venue:"ICLR", year:2026, date:"May 2026", type:"conference", citations:0, links:{paper:"https://arxiv.org/abs/2508.01148"} },
  // ── 2025 ──
  { title:"Disentangling Likes and Dislikes in Personalized Generative Explainable Recommendation", authors:["Ryotaro Shimizu","Takashi Wada","Yu Wang","Johannes Kruse","Sean O'Brien","Sai HtaungKham","Linxin Song","Yuya Yoshikawa","Yuki Saito","Fugee Tsung","Masayuki Goto","Julian McAuley"], venue:"The Web Conference (WWW)", year:2025, date:"Apr 2025", type:"conference", citations:2, links:{paper:"https://doi.org/10.1145/3696410.3714583"} },
  { title:"Mastering Task Arithmetic: τJp as a Key Indicator for Weight Disentanglement", authors:["Kotaro Yoshida","Yuji Naraki","Takafumi Horie","Ryosuke Yamaki","Ryotaro Shimizu","Yuki Saito","Julian McAuley","Hiroki Naganuma"], venue:"ICLR", year:2025, date:"Apr 2025", type:"conference", citations:0, links:{paper:"https://openreview.net/forum?id=1VwWi6zbxs"} },
  { title:"Explaining Black-box Model Predictions via Two-level Nested Feature Attributions with Consistency Property", authors:["Yuya Yoshikawa","Masanari Kimura","Ryotaro Shimizu","Yuki Saito"], venue:"IJCAI", year:2025, date:"Aug 2025", type:"conference", citations:0, links:{} },
  { title:"Discovering Knowledge Deficiencies of Language Models on Massive Knowledge Base", authors:["Linxin Song","Xuwei Ding","Jieyu Zhang","Taiwei Shi","Ryotaro Shimizu","Rahul Gupta","Yang Liu","Jian Kang","Jieyu Zhao"], venue:"COLM", year:2025, date:"Oct 2025", type:"conference", citations:0, links:{} },
  { title:"Static Word Embeddings for Sentence Semantic Representation", authors:["Takashi Wada","Yuki Hirakawa","Ryotaro Shimizu","Takahiro Kawashima","Yuki Saito"], venue:"EMNLP", year:2025, date:"Nov 2025", type:"conference", citations:0, links:{} },
  { title:"Attributed Synthetic Data Generation for Zero-shot Domain-specific Image Classification", authors:["Shijian Wang","Linxin Song","Ryotaro Shimizu","Masayuki Goto","Hanqian Wu"], venue:"ICME", year:2025, date:"Jun 2025", type:"conference", citations:0, links:{} },
  { title:"Normative Alignment of Recommender Systems via Internal Label Shift", authors:["Ryotaro Shimizu","et al."], venue:"RecSys (Late-Breaking Results)", year:2025, date:"Sep 2025", type:"conference", citations:0, links:{} },
  { title:"Optimizing Pre-training via Target-Aware Source Data Selection", authors:["Kanyu Miyoshi","Ryotaro Shimizu","Linxin Song","Masayuki Goto"], venue:"Knowledge-Based Systems", year:2025, type:"journal", citations:0, links:{} },
  { title:"Generating Realistic Synthetic Tabular Data with Integrated LLM and Diffusion Models", authors:["Tokimasa Isomura","Ryotaro Shimizu","Masayuki Goto"], venue:"Neurocomputing", year:2025, date:"Sep 2025", type:"journal", citations:0, links:{} },
  { title:"Continual Learning Model with Dynamic Adaptation and Flexibility for Incremental Classes", authors:["Minami Hotta","Noriko Ogasawara","Kengo Miyajima","Ryotaro Shimizu","Masayuki Goto"], venue:"Applied Sciences", year:2025, date:"Nov 2025", type:"journal", citations:0, links:{} },
  { title:"商品階層を自動構造化するトピックモデルの提案と小売販売データ分析への適用", authors:["藤田柊子","石井達也","磯村時将","米田安希子","清水良太郎","後藤正幸"], venue:"日本経営工学会論文誌", year:2025, type:"journal", citations:0, links:{paper:"https://www.jstage.jst.go.jp/article/jima/76/2/76_37/_article/-char/ja/"} },
  { title:"Sparse Attention Is All You Need for Pre-training on Tabular Data", authors:["Tokimasa Isomura","Ryotaro Shimizu","Masayuki Goto"], venue:"Neural Computing and Applications", year:2025, date:"Jan 2025", type:"journal", citations:8, links:{paper:"https://doi.org/10.1007/s00521-024-10698-x"} },
  { title:"LARE: Latent Augmentation using Regional Embedding with Vision-Language Model", authors:["Kosuke Sakurai","Tatsuya Ishii","Ryotaro Shimizu","Linxin Song","Masayuki Goto"], venue:"Machine Learning with Applications", year:2025, date:"May 2025", type:"journal", citations:0, links:{paper:"https://arxiv.org/abs/2409.12597"} },
  { title:"Template Matters: Understanding the Role of Instruction Templates in Multimodal Language Model Evaluation and Training", authors:["Shijian Wang","Linxin Song","Jieyu Zhang","Ryotaro Shimizu","Ao Luo","Li Yao","Cunjian Chen","Julian McAuley","Hanqian Wu"], venue:"ICLR 2025 Workshop", year:2025, date:"Apr 2025", type:"workshop", citations:0, links:{} },
  { title:"Investigating the Scaling Effect of Instruction Templates for Training Multimodal Language Model", authors:["Shijian Wang","Linxin Song","Jieyu Zhang","Ryotaro Shimizu","Ao Luo","Li Yao","Cunjian Chen","Julian McAuley","Hanqian Wu"], venue:"CVPR 2025 Workshop", year:2025, date:"Jun 2025", type:"workshop", citations:0, links:{} },
  { title:"On Fairness of Task Arithmetic: The Role of Task Vectors", authors:["Laura Gomezjurado Gonzalez","Hiroki Naganuma","Kotaro Yoshida","Takafumi Horie","Yuji Naraki","Ryotaro Shimizu"], venue:"NeurIPS 2025 Workshop", year:2025, date:"Dec 2025", type:"workshop", citations:0, links:{} },
  { title:"Discovering Knowledge Deficiencies of Language Models on Massive Knowledge Base", authors:["Linxin Song","Xuwei Ding","Jieyu Zhang","Taiwei Shi","Ryotaro Shimizu","Rahul Gupta","Yang Liu","Jian Kang","Jieyu Zhao"], venue:"NeurIPS 2025 Workshop", year:2025, date:"Dec 2025", type:"workshop", citations:0, links:{} },
  { title:"自己説明型モデルが獲得した説明能力は転移可能か？", authors:["Yuya Yoshikawa","Ryotaro Shimizu","Takahiro Kawashima","Yuki Saito"], venue:"IBIS 2025", year:2025, date:"Nov 2025", type:"domestic", citations:0, links:{} },
  { title:"A Method for Fashion Image Retrieval Utilizing Pose Correction Based on a Diffusion Model", authors:["Minami Hotta","Ryotaro Shimizu","Masayuki Goto"], venue:"APIEMS 2025", year:2025, date:"Nov 2025", type:"conference", citations:0, links:{} },
  { title:"An Image Classification Model of RGB-D Feature Fusion and Interaction Analysis via Attention Sharing", authors:["Ryosuke Saraya","Ryotaro Shimizu","Masayuki Goto"], venue:"APIEMS 2025", year:2025, date:"Nov 2025", type:"conference", citations:0, links:{} },
  { title:"A Study on Joint Modeling of Item and Purchase Time in Sequential Recommendation", authors:["Takahiro Uemukai","Ryotaro Shimizu","Masayuki Goto"], venue:"APIEMS 2025", year:2025, date:"Nov 2025", type:"conference", citations:0, links:{} },
  { title:"On the Pattern Recognition in 4-Dimensional Dynamic Point Cloud Time Series: Improvement of the Method Using Pre-trained Static 3-Dimensional Point Cloud Models", authors:["Kosuke Sakurai","Ryotaro Shimizu","Masayuki Goto"], venue:"APIEMS 2025", year:2025, date:"Nov 2025", type:"conference", citations:0, links:{} },
  { title:"4D群AIにおける知識転移フレームワークの提案と効率化", authors:["櫻井洸介","清水良太郎","後藤正幸"], venue:"第7回 日本イーコマース学会 全国研究発表大会", year:2025, date:"Nov 2025", type:"domestic", citations:0, links:{} },
  { title:"解釈性の高い深度情報を用いた画像認識モデルの改良とその実応用に関する一考察", authors:["更家峻介","清水良太郎","後藤正幸"], venue:"第7回 日本イーコマース学会 全国研究発表大会", year:2025, date:"Nov 2025", type:"domestic", citations:0, links:{} },
  { title:"RGB-Dデータに対する多様な画像認識タスクを可能とする深層学習モデルに関する一考察", authors:["更家崚介","清水良太郎","後藤正幸"], venue:"日本経営工学会 2025年秋季大会", year:2025, date:"Oct 2025", type:"domestic", citations:0, links:{} },
  { title:"3D事前学習モデルを活用した4D点群動画理解に関する一考察", authors:["櫻井洸介","清水良太郎","後藤正幸"], venue:"日本経営工学会 2025年秋季大会", year:2025, date:"Oct 2025", type:"domestic", citations:0, links:{} },
  { title:"時系列推薦を対象とした購入アイテムと購入タイミングを同時予測するマルチタスク予測モデル", authors:["上向崇裕","清水良太郎","後藤正幸"], venue:"日本経営工学会 2025年秋季大会", year:2025, date:"Oct 2025", type:"domestic", citations:0, links:{} },
  { title:"購買間隔を考慮した時系列推薦モデルに基づくユーザ分析の検討", authors:["上向崇裕","清水良太郎","後藤正幸"], venue:"電子情報通信学会ソサイエティ大会 2025", year:2025, date:"Sep 2025", type:"domestic", citations:0, links:{} },
  { title:"大規模画像言語モデルを用いた優先的データ拡張手法の提案", authors:["櫻井洸介","清水良太郎","後藤正幸"], venue:"電子情報通信学会ソサイエティ大会 2025", year:2025, date:"Sep 2025", type:"domestic", citations:0, links:{} },
  { title:"深度情報を活用した画像分類モデルとその解釈性に関する検討", authors:["更家崚介","清水良太郎","後藤正幸"], venue:"電子情報通信学会ソサイエティ大会 2025", year:2025, date:"Sep 2025", type:"domestic", citations:0, links:{} },
  { title:"Fashionability-Enhancing Outfit Image Editing with Conditional Diffusion Models", authors:["Qice Qin","Yuki Hirakawa","Ryotaro Shimizu","Takuya Furusawa","Edgar Simo-Serra"], venue:"WACV 2025 Workshop", year:2025, date:"Mar 2025", type:"workshop", citations:0, links:{} },
  { title:"曖昧なファッション表現を扱う画像検索のための一般投稿データ対応法の検討", authors:["堀田南","清水良太郎","平川優伎","後藤正幸"], venue:"MIRU 2025", year:2025, date:"Jul 2025", type:"domestic", citations:0, links:{} },
  { title:"衣服のサイズを考慮した着用画像生成の検討", authors:["古澤拓也","清水良太郎","和田崇史"], venue:"MIRU 2025", year:2025, date:"Jul 2025", type:"domestic", citations:0, links:{} },
  { title:"Revisiting Static Word Embeddings as Efficient Sentence Encoders", authors:["Takashi Wada","Yuki Hirakawa","Ryotaro Shimizu","Takahiro Kawashima","Yuki Saito"], venue:"COLING", year:2025, date:"Jan 2025", type:"conference", citations:0, links:{} },
  { title:"文の埋め込みに効果的な静的単語ベクトルの獲得", authors:["和田崇史","平川優伎","清水良太郎","川島貴大","斎藤侑輝"], venue:"NLP 2025", year:2025, date:"Mar 2025", type:"domestic", citations:0, links:{} },
  { title:"Eコマース検索結果におけるクエリに応じたサムネイル最適化に関する実験的研究", authors:["伊澤遼平","吉本一平","広渡朱莉","清水良太郎","斎藤侑輝","和田崇史"], venue:"JSAI 2025", year:2025, date:"May 2025", type:"domestic", citations:0, links:{} },
  { title:"Task Analogiesにおけるモデル線形化の有効性の検証", authors:["吉田晃太朗","堀江孝文","槙木悠士","清水良太郎","山木良輔","長沼大樹"], venue:"JSAI 2025", year:2025, date:"May 2025", type:"domestic", citations:0, links:{} },
  { title:"画像言語参照プロンプトを適用したSegment Anything ModelによるFew-shotセグメンテーションモデル", authors:["櫻井洸介","清水良太郎","後藤正幸"], venue:"JSAI 2025", year:2025, date:"May 2025", type:"domestic", citations:0, links:{} },
  { title:"深度情報を用いた画像識別における解釈性向上に関する一考察", authors:["更家嘉介","清水良太郎","後藤正幸"], venue:"JSAI 2025", year:2025, date:"May 2025", type:"domestic", citations:0, links:{} },
  { title:"増分クラスに対する動的対応と柔軟性を有する継続学習モデルの提案", authors:["堀田南","小笠原のりこ","宮島健悟","清水良太郎","後藤正幸"], venue:"JSAI 2025", year:2025, date:"May 2025", type:"domestic", citations:0, links:{} },
  { title:"置換不変ニューラルネットワークによる集合データマッチングのための全身画像を用いた事前学習", authors:["秦淇策","清水良太郎","平川優伎","シモセラ・エドガー"], venue:"MIRU 2025", year:2025, date:"Jul 2025", type:"domestic", citations:0, links:{} },
  { title:"Masked Language Prompting for Data Augmentation in Few-shot Style Recognition", authors:["Yuki Hirakawa","Ryotaro Shimizu"], venue:"MIRU 2025", year:2025, date:"Jul 2025", type:"domestic", citations:0, links:{} },
  // ── 2024 ──
  { title:"LLMOverTab: Tabular Data Augmentation with Language Model-Driven Oversampling", authors:["Tokimasa Isomura","Ryotaro Shimizu","Masayuki Goto"], venue:"Expert Systems with Applications", year:2024, date:"Nov 2024", type:"journal", citations:6, links:{} },
  { title:"Effectiveness Verification Framework for Coupon Distribution Marketing Measure Considering Users' Potential Purchase Intentions", authors:["Akiko Yoneda","Ryotaro Shimizu","Shion Sakurai","Makoto Kawata","Haruka Yamashita","Masayuki Goto"], venue:"Cogent Engineering", year:2024, date:"Jan 2024", type:"journal", citations:2, links:{paper:"https://www.tandfonline.com/doi/full/10.1080/23311916.2024.2307718"} },
  { title:"Optimizing FT-Transformer: Sparse Attention for Improved Performance and Interpretability", authors:["Tokimasa Isomura","Ryotaro Shimizu","Masayuki Goto"], venue:"Industrial Engineering and Management Systems", year:2024, date:"Jun 2024", type:"journal", citations:8, links:{} },
  { title:"An Empirical Analysis of GPT-4V's Performance on Fashion Aesthetic Evaluation", authors:["Yuki Hirakawa","Takashi Wada","Kazuya Morishita","Ryotaro Shimizu","Takuya Furusawa","Sai Htaung Kham","Yuki Saito"], venue:"SIGGRAPH Asia 2024 Technical Communications", year:2024, date:"Dec 2024", type:"workshop", citations:4, links:{} },
  { title:"A Fashion Item Recommendation Model in Hyperbolic Space", authors:["Ryotaro Shimizu","Yu Wang","Masanari Kimura","Yuki Hirakawa","Takashi Wada","Yuki Saito","Julian McAuley"], venue:"CVPR 2024 Workshop", year:2024, date:"Jun 2024", type:"workshop", citations:0, links:{} },
  { title:"Attributed Synthetic Data Generation for Zero-shot Image Classification", authors:["Shijian Wang","Linxin Song","Ryotaro Shimizu","Masayuki Goto","Hanqian Wu"], venue:"CVPR 2024 Workshop", year:2024, date:"Jun 2024", type:"workshop", citations:0, links:{} },
  { title:"大規模視覚言語モデルを用いた「似合う」の自動評価法", authors:["平川優伎","森下和哉","和田崇史","清水良太郎","古澤拓也","Sai Htaung Kham","斎藤侑輝"], venue:"MIRU 2024", year:2024, date:"Jul 2024", type:"domestic", citations:0, links:{} },
  { title:"商品階層を自動構造化するトピックモデルの提案と小売販売データ分析への適用", authors:["藤田梓子","清水良太郎","石井達也","磯村時将","米田安希子","後藤正幸"], venue:"データ解析コンペティション JIMA予選会", year:2024, date:"Feb 2024", type:"domestic", citations:0, links:{} },
  { title:"商品階層を自動構造化するトピックモデルの提案と小売販売データ分析への適用", authors:["藤田梓子","清水良太郎","石井達也","磯村時将","米田安希子","後藤正幸"], venue:"データ解析コンペティション 決勝大会", year:2024, date:"Mar 2024", type:"domestic", citations:0, links:{} },
  { title:"Instance AttributionとFeature Attributionの一貫性制約を満たす集合関数の局所説明法", authors:["吉川友也","木村正成","清水良太郎","斎藤侑輝"], venue:"JSAI 2024", year:2024, date:"May 2024", type:"domestic", citations:0, links:{} },
  { title:"大規模画像言語モデルを用いた領域埋め込みによる画像分類手法に関する一考察", authors:["櫻井洸介","石井達也","清水良太郎","宋林鑫","後藤正幸"], venue:"JSAI 2024", year:2024, date:"May 2024", type:"domestic", citations:0, links:{} },
  { title:"不確実性が高い事象の確率的予測と解釈を可能とするGaussian-SAINTの提案", authors:["更家嘉介","磯村時将","清水良太郎","後藤正幸"], venue:"JSAI 2024", year:2024, date:"May 2024", type:"domestic", citations:0, links:{} },
  { title:"A closer Look at Task Analogies: Insights from Function and Parameter Space", authors:["Kotaro Yoshida","Yuji Naraki","Takafumi Horie","Ryosuke Yamaki","Ryotaro Shimizu","Yuki Saito","Hiroki Naganuma"], venue:"YANS 2024", year:2024, date:"Sep 2024", type:"domestic", citations:0, links:{} },
  { title:"継続的メール配信の影響を考慮したメール開封要因分析モデル", authors:["阪井優太","清水良太郎","後藤正幸"], venue:"日本計算機統計学会シンポジウム", year:2024, date:"Oct 2024", type:"domestic", citations:0, links:{} },
  { title:"大規模言語モデルと拡散モデルの統合による表形式データ生成手法の提案", authors:["磯村時将","清水良太郎","後藤正幸"], venue:"日本計算機統計学会シンポジウム", year:2024, date:"Oct 2024", type:"domestic", citations:0, links:{} },
  { title:"大規模ソースデータの選択的活用によるターゲットモデルの精度向上に関する研究", authors:["三好観悠","清水良太郎","宋林鑫","後藤正幸"], venue:"日本計算機統計学会シンポジウム", year:2024, date:"Oct 2024", type:"domestic", citations:0, links:{} },
  { title:"Task arithmeticにおける重み分離のための正則化手法の提案", authors:["Kotaro Yoshida","Yuji Naraki","Ryosuke Yamaki","Takafumi Horie","Ryotaro Shimizu","Yuki Saito","Julian McAuley","Hiroki Naganuma"], venue:"IBIS 2024", year:2024, date:"Oct 2024", type:"domestic", citations:0, links:{} },
  { title:"単独アノテーターにおける効率的なアノテーション方法の提案", authors:["岩井理紗","山下遥","清水良太郎"], venue:"経営工学会", year:2024, date:"Oct 2024", type:"domestic", citations:0, links:{} },
  { title:"商品階層を自動構造化するトピックモデルの提案と小売販売データ分析への適用", authors:["藤田梓子","清水良太郎","後藤正幸"], venue:"経営工学会", year:2024, date:"Oct 2024", type:"domestic", citations:0, links:{} },
  { title:"Synthetic Tabular Data Generation based on Integration of Large Language Models and Diffusion Techniques", authors:["Tokimasa Isomura","Ryotaro Shimizu","Masayuki Goto"], venue:"APIEMS 2024", year:2024, date:"Nov 2024", type:"conference", citations:0, links:{} },
  { title:"Multi-Label Image Data Processing via Domain Adaptation", authors:["Kanyu Miyoshi","Ryotaro Shimizu","Linxin Song","Masayuki Goto"], venue:"APIEMS 2024", year:2024, date:"Nov 2024", type:"conference", citations:0, links:{} },
  { title:"Gain Guided Selection Priority Data Augmentation Based on Regional Embedding with Vision-Language Model", authors:["Kosuke Sakurai","Ryotaro Shimizu","Masayuki Goto"], venue:"CIE 2024", year:2024, date:"Dec 2024", type:"conference", citations:0, links:{} },
  { title:"Zero-Shot Explainable Time Series Forecasting based on Large Language Model", authors:["Takahiro Uemukai","Ryotaro Shimizu","Masayuki Goto"], venue:"CIE 2024", year:2024, date:"Dec 2024", type:"conference", citations:0, links:{} },
  { title:"GAUSSIAN-SAINT: A Probabilistic Predictive Deep Learning Model for Uncertainties with Interpretation from Two Perspectives", authors:["Ryosuke Saraya","Tokimasa Isomura","Ryotaro Shimizu","Masayuki Goto"], venue:"CIE 2024", year:2024, date:"Dec 2024", type:"conference", citations:0, links:{} },
  { title:"A study on efficient annotation method for single annotations", authors:["Risa Iwai","Ryotaro Shimizu","Haruka Yamashita"], venue:"CIE 2024", year:2024, date:"Dec 2024", type:"conference", citations:0, links:{} },
  { title:"Mastering Task Arithmetic: tauJp as a Key Indicator for Weight Disentanglement", authors:["Kotaro Yoshida","Yuji Naraki","Takafumi Horie","Ryosuke Yamaki","Ryotaro Shimizu","Yuki Saito","Julian McAuley","Hiroki Naganuma"], venue:"NeurIPS 2024 Workshop", year:2024, date:"Dec 2024", type:"workshop", citations:0, links:{} },
  // ── Preprints (arXiv) ──
  { title:"Fashion-Specific Attributes Interpretation via Dual Gaussian Visual-Semantic Embedding", authors:["Ryotaro Shimizu","Masanari Kimura","Masayuki Goto"], venue:"arXiv", year:2022, date:"Oct 2022", type:"preprint", citations:0, links:{paper:"https://arxiv.org/abs/2210.17417"} },
  // ── Preprints (arXiv) ──
  { title:"On permutation-invariant neural networks", authors:["Masanari Kimura","Ryotaro Shimizu","Yuki Hirakawa","Ryosuke Goto","Yuki Saito"], venue:"arXiv", year:2024, date:"Mar 2024", type:"preprint", citations:0, links:{paper:"https://arxiv.org/abs/2403.17410"} },
  // ── Preprints (arXiv) ──
  { title:"Transferring Visual Explainability of Self-Explaining Models to Prediction-Only Models without Additional Training", authors:["Yuya Yoshikawa","Ryotaro Shimizu","Takahiro Kawashima","Yuki Saito"], venue:"arXiv", year:2025, date:"Jul 2025", type:"preprint", citations:0, links:{paper:"https://arxiv.org/abs/2507.04380"} },
  { title:"Vision and Language Reference Prompt into SAM for Few-shot Segmentation", authors:["Kosuke Sakurai","Ryotaro Shimizu","Masayuki Goto"], venue:"arXiv", year:2025, date:"Feb 2025", type:"preprint", citations:0, links:{paper:"https://arxiv.org/abs/2502.00719"} },
  // ── 2023 ──
  { title:"Partial Visual-Semantic Embedding: Fine-Grained Outfit Image Representation with Massive Volumes of Tags via Angular-Based Contrastive Learning", authors:["Ryotaro Shimizu","Takuma Nakamura","Masayuki Goto"], venue:"Knowledge-Based Systems", year:2023, date:"Oct 2023", type:"journal", citations:6, links:{} },
  { title:"Multiple Treatment Effect Estimation for Business Analytics Using Observational Data", authors:["Ryotaro Shimizu","Masayuki Goto"], venue:"Cogent Engineering", year:2023, date:"Dec 2023", type:"journal", citations:4, links:{paper:"https://www.tandfonline.com/doi/full/10.1080/23311916.2023.2300557"} },
  { title:"A Method for Advanced Analysis of Item Browsing Data Considering User Interest Durations Using Parameters Estimated from Hidden Semi-Markov Model", authors:["Kirin Tsuchiya","Yuki Tsuboi","Ryotaro Shimizu","Masayuki Goto"], venue:"Industrial Engineering & Management Systems", year:2023, date:"Dec 2023", type:"journal", citations:0, links:{} },
  { title:"最大次数が未知の多項式回帰モデルに対するスパース推定に関する一考察", authors:["井上一磨","清水良太郎","須子統太","後藤正幸"], venue:"情報処理学会論文誌", year:2023, type:"journal", citations:0, links:{} },
  { title:"Fashion-Specific Ambiguous Expression Interpretation with Partial Visual-Semantic Embedding", authors:["Ryotaro Shimizu","Takuma Nakamura","Masayuki Goto"], venue:"CVPR 2023 Workshop", year:2023, date:"Jun 2023", type:"workshop", citations:4, links:{paper:"https://openaccess.thecvf.com/content/CVPR2023W/CVFAD/html/Shimizu_Fashion-Specific_Ambiguous_Expression_Interpretation_With_Partial_Visual-Semantic_Embedding_CVPRW_2023_paper.html"} },
  { title:"ファッション特有の曖昧な表現を解釈する Fashion Intelligence System の応用と今後の展開", authors:["清水良太郎","斎藤侑輝","後藤正幸"], venue:"JSAI 2023", year:2023, date:"Jun 2023", type:"domestic", citations:0, links:{} },
  { title:"Recommendation Item Selection Algorithm Considering the Recommendation Region in the Embedding Space", authors:["Tomoki Amano","Ryotaro Shimizu","Masayuki Goto"], venue:"Industrial Engineering & Management Systems", year:2023, type:"journal", citations:0, links:{} },
  { title:"ユーザの潜在的な購買意欲を考慮した機械学習モデルに基づくクーポン配布施策の効果検証モデル", authors:["米田安希子","清水良太郎","桜井詩音","川田心","山下遥","後藤正幸"], venue:"JSAI 2023", year:2023, date:"Jun 2023", type:"domestic", citations:0, links:{} },
  { title:"画像情報及び言語情報に基づくファッションコーディネート投稿の推薦", authors:["岩井理紗","清水良太郎","山下遥"], venue:"JSAI 2023", year:2023, date:"Jun 2023", type:"domestic", citations:0, links:{} },
  { title:"FT-Transformerの精度向上と効率化に関する一考察", authors:["磯村時将","天野智貴","清水良太郎","後藤正幸"], venue:"JSAI 2023", year:2023, date:"Jun 2023", type:"domestic", citations:0, links:{} },
  { title:"レビュー文書データを対象としたBERTとSHAPによる評価値向上要因分析モデル", authors:["渡邊真己子","山田晃輝","清水良太郎","鈴木佐俊","後藤正幸"], venue:"JSAI 2023", year:2023, date:"Jun 2023", type:"domestic", citations:0, links:{} },
  { title:"最大次数が未知の多項式回帰モデルに対するスパース推定に関する一考察", authors:["井上一磨","清水良太郎","須子統太","後藤正幸"], venue:"MPS研究会", year:2023, date:"Jun 2023", type:"domestic", citations:0, links:{} },
  { title:"A Study on Performance Improvement and Interpretability of FT-Transformer", authors:["Tokimasa Isomura","Tomoki Amano","Ryotaro Shimizu","Masayuki Goto"], venue:"Asian Network for Quality Congress 2023", year:2023, date:"Oct 2023", type:"conference", citations:0, links:{} },
  { title:"Factor Analysis Framework of Review Data based on BERT and SHAP for Improving Customer Satisfaction", authors:["Mamiko Watanabe","Koki Yamada","Ryotaro Shimizu","Satoshi Suzuki","Masayuki Goto"], venue:"Asian Network for Quality Congress 2023", year:2023, date:"Oct 2023", type:"conference", citations:0, links:{} },
  { title:"Machine Learning Based Experimental Design and Effectiveness Verification for Coupon Measures with Different Discount Amounts", authors:["Akiko Yoneda","Ryotaro Shimizu","Shion Sakurai","Shin Kawata","Haruka Yamashita","Masayuki Goto"], venue:"APIEMS 2023", year:2023, date:"Oct 2023", type:"conference", citations:0, links:{} },
  { title:"A Study on Recommendation of Fashion Coordination Posts Based on Image and Linguistic Information", authors:["Risa Iwai","Ryotaro Shimizu","Haruka Yamashita"], venue:"APIEMS 2023", year:2023, date:"Oct 2023", type:"conference", citations:0, links:{} },
  { title:"A Study on Image Generation Considering User Attribute Information by VQ-Conditional StyleGAN2", authors:["Oike Tatsuki","Ryotaro Shimizu","Haruka Yamashita"], venue:"APIEMS 2023", year:2023, date:"Oct 2023", type:"conference", citations:0, links:{} },
  { title:"An Improved Algorithm Based on Self-Supervised Learning for Multi-Tag Prediction of Extreme Weather Events", authors:["Tomoki Amano","Ryotaro Shimizu","Masayuki Goto"], venue:"APIEMS 2023", year:2023, date:"Oct 2023", type:"conference", citations:0, links:{} },
  { title:"A Novel Latent Class Model for Estimating the Relationship Between User Preferences and Item Image Features", authors:["Kirin Tsuchiya","Ryotaro Shimizu","Masayuki Goto"], venue:"APIEMS 2023", year:2023, date:"Oct 2023", type:"conference", citations:0, links:{} },
  { title:"機械学習に基づく複数種類のクーポン配布施策の実験計画および効果検証モデル", authors:["米田安希子","清水良太郎","桜井詩音","川田心","山下遥","後藤正幸"], venue:"SITA 2023", year:2023, date:"Nov 2023", type:"domestic", citations:0, links:{} },
  { title:"マルチタスク学習に基づく極端な気象タグの予測アルゴリズムに関する一考察", authors:["天野智貴","清水良太郎","後藤正幸","吉開朋弘"], venue:"SITA 2023", year:2023, date:"Nov 2023", type:"domestic", citations:0, links:{} },
  { title:"顧客の嗜好と商品画像特徴量の関係性を推定する新たな潜在クラスモデルの提案", authors:["土屋希琳","清水良太郎","後藤正幸"], venue:"SITA 2023", year:2023, date:"Nov 2023", type:"domestic", citations:0, links:{} },
  { title:"画像言語モデルに基づく曖昧なファッション特有の表現を解釈するシステム", authors:["清水良太郎","斎藤侑輝","後藤正幸"], venue:"CCSE 2023", year:2023, date:"Dec 2023", type:"domestic", citations:0, links:{} },
  // ── 2022 ──
  { title:"Fashion Intelligence System: An Outfit Interpretation Utilizing Images and Rich Abstract Tags", authors:["Ryotaro Shimizu","Yuki Saito","Megumi Matsutani","Masayuki Goto"], venue:"Expert Systems with Applications", year:2022, date:"Nov 2022", type:"journal", citations:23, links:{} },
  { title:"複数の施策を対象とした処置効果推定手法に関する一考察", authors:["坪井優樹","阪井優太","清水良太郎","後藤正幸"], venue:"情報処理学会 第84回全国大会", year:2022, date:"Mar 2022", type:"domestic", citations:0, links:{} },
  { title:"Conditional StyleGAN2-adaによるユーザの属性情報を考慮した高評価画像の生成に関する研究", authors:["大池樹","清水良太郎","山下遥"], venue:"情報処理学会 第84回全国大会", year:2022, date:"Mar 2022", type:"domestic", citations:0, links:{} },
  { title:"ユーザの多様性を考慮したクラスタワイズ型機械学習モデルの提案とその解釈方法に関する研究", authors:["三池可奈","清水良太郎","山下遥"], venue:"情報処理学会 第84回全国大会", year:2022, date:"Mar 2022", type:"domestic", citations:0, links:{} },
  { title:"隠れセミマルコフモデルに基づくユーザの嗜好持続性を考慮した商品分析手法に関する一考察", authors:["土屋希琳","坪井優樹","清水良太郎","後藤正幸"], venue:"人工知能学会全国大会（第36回）", year:2022, date:"Jun 2022", type:"domestic", citations:0, links:{} },
  { title:"A study on generation of images with many likes by Conditional StyleGAN2-ada considering user attribute information", authors:["Oike Tatsuki","Haruka Yamashita","Ryotaro Shimizu"], venue:"Asian Network for Quality Congress 2022", year:2022, date:"Oct 2022", type:"conference", citations:0, links:{} },
  { title:"A study on cluster-wise XGBoost model considering user diversity and its interpretation approach", authors:["Kana Mitsubashi","Haruka Yamashita","Ryotaro Shimizu"], venue:"Asian Network for Quality Congress 2022", year:2022, date:"Oct 2022", type:"conference", citations:0, links:{} },
  { title:"A method for item analysis considering duration of user interests based on a hidden semi-markov model", authors:["Kirin Tsuchiya","Yuki Tsuboi","Ryotaro Shimizu","Masayuki Goto"], venue:"Asian Network for Quality Congress 2022", year:2022, date:"Oct 2022", type:"conference", citations:0, links:{} },
  { title:"機械学習に基づくファッション特有の曖昧な表現を自動的に解釈するためのシステム", authors:["清水良太郎","斎藤侑輝","松谷恵","後藤正幸"], venue:"日本経営工学会 秋季大会", year:2022, date:"Nov 2022", type:"domestic", citations:0, links:{} },
  { title:"埋め込み空間における推薦領域を考慮した推薦アイテム獲得手法の提案", authors:["天野智貴","清水良太郎","後藤正幸"], venue:"日本経営工学会 秋季大会", year:2022, date:"Nov 2022", type:"domestic", citations:0, links:{} },
  { title:"Guided LDAによるファッションテーマの抽出及び推薦への応用", authors:["古田博也","山下遥","清水良太郎"], venue:"日本経営工学会 秋季大会", year:2022, date:"Nov 2022", type:"domestic", citations:0, links:{} },
  { title:"CNNを用いた能動学習におけるラベル付与データの選択手法に関する一考察", authors:["益田恵里花","山田晃輝","清水良太郎","後藤正幸"], venue:"日本計算機統計学会 第36回シンポジウム", year:2022, date:"Nov 2022", type:"domestic", citations:0, links:{} },
  { title:"複数のECマーケティング施策を対象とした観察データに基づく効果推定手法", authors:["坪井優樹","阪井優太","清水良太郎","後藤正幸"], venue:"情報理論とその応用シンポジウム (SITA)", year:2022, date:"Nov 2022", type:"domestic", citations:0, links:{} },
  { title:"知識グラフと強化学習に基づく説明可能な推薦のための効率的な経路探索アルゴリズム", authors:["楊冠宇","清水良太郎","山極綾子","後藤正幸"], venue:"情報理論とその応用シンポジウム (SITA)", year:2022, date:"Nov 2022", type:"domestic", citations:0, links:{} },
  { title:"Multiple Treatment Effect Estimation for E-commerce Marketing Using Observational Data", authors:["Yuki Tsuboi","Yuta Sakai","Ryotaro Shimizu","Masayuki Goto"], venue:"APIEMS 2022", year:2022, date:"Dec 2022", type:"conference", citations:0, links:{} },
  { title:"Extraction of fashion themes focusing hashtags based on Guided LDA", authors:["Hiroya Furuta","Haruka Yamashita","Ryotaro Shimizu"], venue:"APIEMS 2022", year:2022, date:"Dec 2022", type:"conference", citations:0, links:{} },
  { title:"Recommendation Item Selection Algorithm Considering the Recommendation Region in the Embedding Space", authors:["Tomoki Amano","Ryotaro Shimizu","Masayuki Goto"], venue:"APIEMS 2022", year:2022, date:"Dec 2022", type:"conference", citations:0, links:{} },
  { title:"An Efficient Path Search Algorithm for Explainable Recommendation Based on Knowledge Graph and Reinforcement Learning", authors:["Guanyu Yang","Ryotaro Shimizu","Ayako Yamagiwa","Masayuki Goto"], venue:"APIEMS 2022", year:2022, date:"Dec 2022", type:"conference", citations:0, links:{} },
  // ── 2021 ──
  { title:"An Explainable Recommendation Framework Based on an Improved Knowledge Graph Attention Network with Massive Volumes of Side Information", authors:["Ryotaro Shimizu","Megumi Matsutani","Masayuki Goto"], venue:"Knowledge-Based Systems", year:2021, date:"Dec 2021", type:"journal", citations:79, links:{} },
  { title:"A Latent Class Analysis for Item Demand Based on Temperature Difference and Store Characteristics", authors:["Yuto Seko","Ryotaro Shimizu","Gendo Kumoi","Tomohiro Yoshikai","Masayuki Goto"], venue:"Industrial Engineering & Management Systems", year:2021, type:"journal", citations:3, links:{} },
  { title:"ファッション系ECサイトにおける多様な補助情報を有したグラフ構造の学習アルゴリズムに関する一考察", authors:["清水良太郎","松谷恵","後藤正幸"], venue:"日本経営工学会 2021年春季大会", year:2021, date:"May 2021", type:"domestic", citations:0, links:{} },
  { title:"仮想通貨取引データに対する敵対的生成ネットワークを用いた分類性能向上手法の検討", authors:["楊冠宇","清水良太郎","雲居玄道","後藤正幸"], venue:"日本経営工学会 2021年春季大会", year:2021, date:"May 2021", type:"domestic", citations:0, links:{} },
  { title:"A discussion on improving fraud detection performance by Generative Adversarial Networks Transactions", authors:["Guanyu Yang","Yuki Tsuboi","Ryotaro Shimizu","Gendo Kumoi","Masayuki Goto"], venue:"The 19th ANQ Congress 2021", year:2021, date:"Oct 2021", type:"conference", citations:0, links:{} },
  { title:"Uplift Modelingを利用したノンコンプライアンスが存在する状況下での説得可能層の推定", authors:["夏堀雄太","清水良太郎","山下遥"], venue:"D-DATa データ科学オンライン研究発表会", year:2021, date:"Aug 2021", type:"domestic", citations:0, links:{} },
  { title:"対照群のデータを考慮したTransformed outcome methodによるコンプライアーの予測とその評価に関する研究", authors:["夏堀雄太","清水良太郎","山下遥"], venue:"日本経営システム学会 第67回全国研究発表大会", year:2021, date:"Nov 2021", type:"domestic", citations:0, links:{} },
  { title:"外部ドメインデータを活用した潜在顧客発見に向けた取り組み", authors:["清水良太郎","柳圭祐"], venue:"CCSE 2021", year:2021, date:"Dec 2021", type:"domestic", citations:0, links:{} },
  // ── 2020 ──
  { title:"Latent Variable Models for Integrated Analysis of Credit and Point Usage History Data on Rewards Credit Card System", authors:["Ryotaro Shimizu","Haruka Yamashita","Masao Ueda","Ranna Tanaka","Tetsuya Tachibana","Masayuki Goto"], venue:"International Business Research", year:2020, type:"journal", citations:2, links:{} },
  // ── 2019 ──
  { title:"How Did the 2015 Political Crisis Affect Nepal in Economic and Social Respects?", authors:["Ryotaro Shimizu","Brenda Bushell","Masayuki Goto"], venue:"Environment and Ecology Research", year:2019, type:"journal", citations:0, links:{} },
  // ── 2018 ──
  { title:"Proposal of a Purchase Behavior Analysis Model on an Electronic Commerce Site Using Questionnaire Data", authors:["Ryotaro Shimizu","Teppei Sakamoto","Haruka Yamashita","Masayuki Goto"], venue:"Total Quality Science", year:2018, date:"Dec 2018", type:"journal", citations:2, links:{} },
  { title:"Consumer Purchasing Behavior Model for Purchase History Data Stored in Credit Card", authors:["Ryotaro Shimizu","Haruka Yamashita","Ranna Tanaka","Masayuki Goto"], venue:"APIEMS 2018", year:2018, date:"Dec 2018", type:"conference", citations:0, links:{} },
  { title:"A Prediction Model of Item Demands Based on Temperature Difference and Store Characteristics", authors:["Yuto Seko","Ryotaro Shimizu","Gendo Kumoi","Masayuki Goto","Tomohiro Yoshikai"], venue:"Asian Network for Quality Congress 2018", year:2018, date:"Sep 2018", type:"conference", citations:0, links:{} },
  { title:"クレジットとポイントを併用可能な多機能クレジットカードにおける利用履歴データの統合分析モデルの提案", authors:["清水良太郎","山下遥","上田雅夫","田中藍奈","後藤正幸"], venue:"SITA 2018", year:2018, date:"Dec 2018", type:"domestic", citations:0, links:{} },
  { title:"クレジットとポイントを併用可能な多機能クレジットカードにおける利用履歴データの統合分析モデルの提案", authors:["清水良太郎","山下遥","上田雅夫","田中藍奈","後藤正幸"], venue:"価値創造マネジメントシンポジウム", year:2018, date:"Dec 2018", type:"domestic", citations:0, links:{} },
  { title:"最大次数が未知の多項式回帰モデルに対するスパース推定に関する一考察", authors:["井上一磨","清水良太郎","須子統太","後藤正幸"], venue:"情報論的学習理論と機械学習研究会", year:2018, date:"Nov 2018", type:"domestic", citations:0, links:{} },
  { title:"気象条件と店舗特性を考慮した商品別需要モデル構築に関する一考察", authors:["世古裕都","清水良太郎","雲居玄道","後藤正幸","吉開朋弘"], venue:"日本経営工学会 2018年春季大会", year:2018, date:"May 2018", type:"domestic", citations:0, links:{} },
  { title:"Tweetデータに基づく料理画像の魅力度定量化モデル", authors:["藤波英輝","清水良太郎","雲居玄道","後藤正幸"], venue:"日本経営工学会 2018年春季大会", year:2018, date:"May 2018", type:"domestic", citations:0, links:{} },
  { title:"ECサイトにおける購買履歴データとアンケートデータを融合した顧客の購買行動分析モデルの提案", authors:["清水良太郎","坂元哲平","山下遥","後藤正幸"], venue:"日本経営工学会 2017年度学生論文発表会", year:2018, date:"Mar 2018", type:"domestic", citations:0, links:{} },
  // ── 2017 ──
  { title:"アンケートデータを考慮したECサイトの購買履歴行動分析モデルの提案", authors:["清水良太郎","坂元哲平","山下遥","後藤正幸"], venue:"日本計算機統計学会第31回シンポジウム", year:2017, date:"Nov 2017", type:"domestic", citations:0, links:{} },
  { title:"Proposal of a Purchase Behavior Analysis Model on EC Site Considering Questionnaire Data", authors:["Ryotaro Shimizu","Teppei Sakamoto","Haruka Yamashita","Masayuki Goto"], venue:"Asian Network for Quality Congress 2017", year:2017, date:"Sep 2017", type:"conference", citations:0, links:{} },
  { title:"アンケートデータを考慮したECサイトの購買履歴分析モデルの提案", authors:["清水良太郎","坂元哲平","山下遥","後藤正幸"], venue:"経営システム", year:2017, date:"Jul 2017", type:"journal", citations:0, links:{} },
  { title:"アンケートデータを考慮したECサイトの購買履歴行動分析モデルの提案", authors:["清水良太郎","坂元哲平","山下遥","後藤正幸"], venue:"日本経営工学会 2017年春季大会", year:2017, date:"May 2017", type:"domestic", citations:0, links:{} },
  { title:"ECサイトにおけるアンケートデータを考慮した購買行動分析モデルの提案", authors:["清水良太郎","坂元哲平","山下遥","後藤正幸"], venue:"データ解析コンペティション JIMA予選会", year:2017, date:"Feb 2017", type:"domestic", citations:0, links:{} },
  // ── 2016 ──
  { title:"Research on the Political Crisis and its Impact on the Economic and Social Sectors in Nepal", authors:["Ryotaro Shimizu","Haruka Yamashita","Masayuki Goto","Brenda Bushell"], venue:"22nd International Interdisciplinary Conference on the Environment", year:2016, date:"Jun 2016", type:"conference", citations:0, links:{} },
];

// ===== Translations =====
const TRANSLATIONS = {
  en: {
    // Nav
    "nav.about":"About","nav.publications":"Publications","nav.talks":"Talks","nav.experience":"Experience","nav.education":"Education","nav.teaching":"Teaching","nav.awards":"Awards","nav.media":"Media","nav.service":"Service","nav.projects":"Projects",
    // Hero
    "hero.greeting":"Hello, I'm",
    "hero.title":"Director, ZOZO Research",
    "hero.affil2":"Visiting Research Fellow, Waseda University",
    "hero.affil3":"Part-time Lecturer, Sophia University",
    "hero.affil4":"Ph.D. in Engineering",
    "hero.stat.pubs":"Publications","hero.stat.cit":"Citations",
    // About
    "about.title":"About",
    "about.p1":"I specialize in translating business objectives into practical AI solutions, with deep expertise in <strong>recommender systems</strong>, <strong>explainable AI</strong>, <strong>computer vision</strong>, <strong>large language models</strong>, and <strong>business data analytics &amp; visualization</strong>. I am particularly interested in <strong>explainable AI for interpreting AI decision-making</strong> and <strong>leveraging AI to make sense of ambiguous, open-ended problems where no single definitive answer exists</strong> (Data &times; AI &times; Ambiguity).",
    "about.p2":"As Director at <a href='https://research.zozo.com/' target='_blank'>ZOZO Research</a>, I lead the ML R&amp;D group, driving service development and industry-academia research collaboration. Blessed with wonderful team members and collaborators, I have published numerous papers and my work has been featured in many media outlets.",
    "about.p3":"I am also passionate about education and mentoring, serving as a Part-time Lecturer at <a href='https://www.sophia.ac.jp/en/' target='_blank'>Sophia University</a> and a Visiting Research Fellow at <a href='https://www.waseda.jp/top/en/' target='_blank'>Waseda University</a>.",
    "about.interests":"Research Interests",
    // Publications
    "pub.title":"Publications","pub.subtitle":"Showing selected highlights only.","pub.showAll":"Show All Publications","pub.showLess":"Show Less","pub.scholarLink":"View on Google Scholar",
    "pub.filter.all":"All","pub.filter.conference":"Conference","pub.filter.journal":"Journal","pub.filter.workshop":"Workshop","pub.filter.preprint":"Preprint","pub.filter.domestic":"Domestic",
    "pub.sort":"Sort","pub.sort.year":"Newest","pub.sort.oldest":"Oldest",
    // News
    "news.title":"News",
    "news.items":[
      {date:"Feb 2026",text:'Launched my personal website to share research and explore collaboration opportunities with diverse researchers and creators.',isNew:true},
      {date:"Feb 2026",text:'Two papers accepted at ICLR 2026 (top ML conference).',isNew:true},
      {date:"Oct 2025",text:'Paper accepted at COLM 2025.',isNew:false},
      {date:"Sep 2025",text:'Paper accepted at <a href="https://zozonext.com/news/20251016_zozoresearch" target="_blank">EMNLP 2025</a>.',isNew:false},
      {date:"Sep 2025",text:'Paper accepted at RecSys 2025 (Late-Breaking Results).',isNew:false},
      {date:"Aug 2025",text:'Research featured in <a href="https://xtech.nikkei.com/atcl/nxt/mag/rob/18/012600001/00173/?P=3" target="_blank">Nikkei Robotics</a>.',isNew:false},
      {date:"Jun 2025",text:'Paper accepted at ICME 2025 (Oral).',isNew:false},
      {date:"May 2025",text:'Joint research with CIT accepted at <a href="https://zozonext.com/news/20250526_zozoresearch" target="_blank">IJCAI 2025</a>.',isNew:false},
      {date:"Feb 2025",text:'Paper accepted at <a href="https://zozonext.com/news/20250203_zozoresearch" target="_blank">The Web Conference (WWW) 2025</a>.',isNew:false},
      {date:"Jan 2025",text:'Paper accepted at <a href="https://zozonext.com/news/20250217_zozoresearch" target="_blank">ICLR 2025</a>.',isNew:false},
      {date:"Aug 2023",text:'Press release on <a href="https://www.waseda.jp/top/news/92745" target="_blank">Fashion AI research</a> (Waseda University × ZOZO Research).',isNew:false},
      {date:"Jun 2023",text:'Research featured in <a href="https://hotozero.com/knowledge/fis/" target="_blank">"Hotozero" interview article</a>.',isNew:false},
      {date:"Dec 2022",text:'Research featured in <a href="https://www.nikkei.com/article/DGKKZO66764470S2A211C2TEB000/" target="_blank">Nikkei (The Nikkei)</a>.',isNew:false},
      {date:"Dec 2022",text:'Research featured in <a href="https://www.fnn.jp/articles/-/452781" target="_blank">FNN (Fuji News Network)</a>.',isNew:false},
      {date:"Nov 2022",text:'<a href="https://www.waseda.jp/top/news/85840" target="_blank">Press release</a> on Fashion Intelligence System (Waseda University × ZOZO Research).',isNew:false},
      {date:"May 2022",text:'A paper I supported writing received the <a href="https://www.jimanet.jp/information/awards/tokubetsu-jissen" target="_blank">JIMA Management Engineering Practice Award</a>: "Visualization of Customer Behavior Using Video Analytics at an Automobile Dealership" (<a href="https://www.azest.co.jp/news/info/news-355/" target="_blank">AZEST</a>).',isNew:false},
      {date:"Mar 2019",text:'Received Best Student Award (Top Graduate) from Waseda University, M.Eng. in Management Systems Engineering.',isNew:false},
      {date:"May 2017",text:'Received <a href="https://www.jimanet.jp/information/awards/best-presentation-award" target="_blank">Best Presentation Award</a> at JIMA Spring Conference.',isNew:false},
      {date:"Apr 2017",text:'Dashboard exhibited at Tableau Conference On Tour Tokyo.',isNew:false},
      {date:"Nov 2016",text:'Attended Tableau Conference 2016 at Austin.',isNew:false}
    ],
    // Talks
    "talks.title":"Talks & Presentations",
    "talks.invited":"Invited Talk","talks.award":"Award Talk","talks.presentation":"Presentation","talks.conference":"Conference","talks.workshop":"Workshop","talks.domestic":"Domestic",
    "talks.confTitle":"Conference Presentations","talks.confDesc":"Oral/poster presentations at top-tier international conferences worldwide.",
    "talks.wsDesc":"Workshop presentations at major computer vision and ML conferences.",
    "talks.domesticDesc":"Presentations at Japanese domestic conferences. Best Research Award at JSAI 2023.",
    // Experience
    "exp.title":"Professional Experience",
    "exp.zozo.dir":"Director, Deployment Department","exp.zozo.dir.d":"Launched and leading a department dedicated to researching and developing AI technologies specialized for ZOZO's services and deploying them into production systems.",
    "exp.zozo.sm":"Senior Manager / Lead Research Scientist","exp.zozo.sm.d":"Led a 10+ member ML research team. Published at top conferences (WWW, ICLR, IJCAI, EMNLP).",
    "exp.zozo.lead":"Lead Research Scientist","exp.zozo.lead.d":"Led applied ML research on fashion intelligence, recommender systems, and explainable AI. Spearheaded collaborative research with universities and industry partners.",
    "exp.zozo.rs":"Research Scientist","exp.zozo.rs.d":"Also engaged in data science and ML engineering for business applications, including building AutoML pipelines with Vertex AI and leading cross-company data utilization projects within the group.",
    "exp.ucsd":"UC San Diego","exp.ucsd.r":"Visiting Research Fellow, Computer Science Department","exp.ucsd.d":"Research on recommender systems and large-scale model fine-tuning at <a href='https://cseweb.ucsd.edu//~jmcauley/' target='_blank'>Julian McAuley Lab</a>. Published multiple papers at international conferences.",
    "exp.sophia":"Sophia University","exp.sophia.r":"Part-time Lecturer, Faculty of Science and Technology","exp.sophia.d":"Teaching data analysis, statistical modeling, machine learning, and Python programming. Student evaluation: 4.8/5.0.",
    "exp.waseda.dsi":"Waseda University","exp.waseda.dsi.r":"Visiting Research Fellow, Data Science Institute","exp.waseda.dsi.d":"Research supervision and mentoring of undergraduate and graduate students at <a href='https://www.it.mgmt.waseda.ac.jp/index.html' target='_blank'>Goto Lab</a>.",
    "exp.dena":"DeNA Co., Ltd.","exp.dena.r":"Software Developer","exp.dena.d":"Backend development (Java, GCP) for global mobile game titles supporting millions of users.",
    "exp.pksha":"PKSHA Technology","exp.pksha.r":"Machine Learning Engineering Intern","exp.pksha.d":"Machine learning engineering internship.",
    "exp.startree":"StarTree Inc.","exp.startree.r":"Analytics Team Leader","exp.startree.d":"Led analytics team using Python and Tableau to analyze HR data for various companies.",
    "exp.azest":"AZEST Inc.","exp.azest.r":"Data Science Intern","exp.azest.d":"Data analytics and BI using Tableau and Power BI.",
    "exp.toreta":"Toreta Inc.","exp.toreta.r":"Software Development Intern","exp.toreta.d":"Full-stack development internship at a restaurant tech startup.",
    // Education
    "edu.title":"Education",
    "edu.waseda":"Waseda University","edu.waseda.hs":"Waseda University Senior High School",
    "edu.phd":"Ph.D. in Engineering (Industrial & Management Systems Engineering)","edu.phd.h":["Early graduation","Inaugural recipient of the <a href='https://corp.zozo.com/news/20180914-5649/' target='_blank'>ZOZO Working Professional Doctoral Program</a>","Advisor: <a href='https://www.it.mgmt.waseda.ac.jp/index.html' target='_blank'>Prof. Masayuki Goto</a>","Research: Recommender systems, explainable AI, fashion intelligence"],
    "edu.ms":"Master of Engineering (Management Systems Engineering)","edu.ms.h":["Best Student Award (Top Graduate)","Advisor: <a href='https://www.it.mgmt.waseda.ac.jp/index.html' target='_blank'>Prof. Masayuki Goto</a>","Research 1: Purchase behavior analysis model on EC sites considering questionnaire data","Research 2: Integrated analysis model for multi-function credit card usage history data","Collaborative research with ZOZO, Inc., Odakyu Electric Railway, and Japan Weather Association"],
    "edu.bs":"B.S. in Management Systems Engineering, School of Creative Science and Engineering",
    "edu.hs":"General Course","edu.hs.h":["<a href='https://www.waseda.jp/school/shs/campus/tennis/' target='_blank'>Tennis Club</a> (Currently serving as OB Association Assistant Secretary)"],
    // Teaching
    "teaching.title":"Teaching",
    "teaching.sophia":"Sophia University — Part-time Lecturer","teaching.sophia.d":"Teaching university-wide general education courses on fundamental statistics, data analysis &amp; visualization, application of machine learning methods to business data, and the Python programming skills required for these.",
    "teaching.sophia.score":"/ 5.0 Average Student Evaluation Score","teaching.sophia.note":"Student evaluation score: 4.8/5.0 (most recent year).","teaching.sophia.contact":"Feel free to reach out with questions about the course or suggestions for improvement.",
    "teaching.waseda":"Waseda University — Visiting Research Fellow","teaching.waseda.d":"Research supervision and mentoring of undergraduate and graduate students at the Data Science Institute.",
    "teaching.waseda.streak":"4 Years","teaching.waseda.label":"Consecutive Top Graduate Mentoring","teaching.waseda.note":"Students under my research supervision have graduated as top of their class for 4 consecutive years.",
    "teaching.studentMsg":"To all students I've had the pleasure of working with — whether through lectures, research mentoring, or <a href='https://ut-base.info/circles/122' target='_blank'>HAIT</a> mentoring — if you ever face challenges in your career or research, please don't hesitate to reach out. I'm always happy to support you, no matter how much time has passed. <strong>My door is always open.</strong>",
    // Awards
    "awards.title":"Awards & Honors",
    "awards.items":[
      {year:"Feb 2025",title:"Runner-up, Annual Best Employee Award — ZOZO Group",desc:"Top 10 of 1,700+ employees."},
      {year:"Dec 2024",title:"Best Paper Award — CIE51",desc:"International Conference on Computers and Industrial Engineering."},
      {year:"Nov 2024",title:"Most Excellent Award, Technology Division — INTERSECTION 2024 (LINE Yahoo! Group)",desc:"Awarded the top prize in the Technology Division at INTERSECTION 2024 (LINE Yahoo! Group). Selected as one of 3 from 27,000+ employees."},
      {year:"Oct 2023",title:"Outstanding Paper Award — APIEMS 2023",desc:"Asia Pacific Industrial Engineering and Management Systems Conference."},
      {year:"Jun 2023",title:"Outstanding Paper Award — JSAI Annual Conference",desc:"Awarded for research on fashion image retrieval at the Japanese Society for Artificial Intelligence."},
      {year:"Feb 2023",title:"Most Excellent Award — JUSE Data Analysis Competition",desc:"Awarded the top prize at the 2023 JUSE Data Analysis Competition, JIMA Division. Theme: Proposal of a Topic Model for Automatic Structuring of Product Hierarchies and Its Application to Retail Sales Data Analysis."},
      {year:"Feb 2022",title:"Grand Prix, Annual Best Employee Award — ZOZO Group",desc:"Top 5 of 1,700+ employees."},
      {year:"Mar 2019",title:"Best Student Award — Waseda University, Management Systems Engineering",desc:"Graduated top of class with GPA 3.95."},
      {year:"Feb 2019",title:"Technical Skills Award — JUSE Data Analysis Competition",desc:"JIMA Division award at the 2019 JUSE Data Analysis Competition. Theme: A Study on Attractiveness Factor Analysis of TV Programs Based on Latent Representation Models."},
      {year:"May 2018",title:"Outstanding Student Presentation Award — JIMA Spring Conference",desc:"Japan Industrial Management Association Spring 2018 Student Presentation Competition."},
      {year:"May 2017",title:"Outstanding Student Presentation Award — JIMA Spring Conference",desc:"Japan Industrial Management Association Spring 2017 Conference."},
      {year:"Feb 2017",title:"Technical Skills Award — JUSE Data Analysis Competition",desc:"JIMA Division award at the 2017 JUSE Data Analysis Competition. Theme: Proposal of a Purchase Behavior Analysis Model on EC Sites Considering Questionnaire Data."}
    ],
    // Media
    "media.title":"Media Coverage","media.subtitle":"Research featured in 100+ media outlets. Selected highlights below.",
    "media.more":"And 100+ more media features including major tech outlets...",
    // Service
    "service.title":"Professional Service","service.reviewer":"Reviewer / Program Committee","service.details":"Details","service.note":"Including multiple years of service",
    // Projects
    "projects.title":"Non-Research Projects",
    "projects.tennis":"TaRO's CUP — Tennis Tournament & Community","projects.tennis.d":"Organizing tennis tournaments (TaRO's CUP, now in its 6th+ edition) and building a vibrant community for players of all levels. Partnering with sponsors like Paradiso and Bridgestone Sports.",
    "projects.nepal":"Nepal Japan Project","projects.nepal.d":"International project between Nepal and Japan (2015, 2016). Served as Project Leader in 2016, coordinating cross-cultural exchanges and community development initiatives.",
    "projects.wedding":"Wedding Real-Time Quiz App","projects.wedding.d":"Developed a real-time quiz application for friends' weddings, supporting 100+ concurrent WebSocket connections. Used at 3 wedding events.",
    "projects.apps":"Personal Apps & Web Development","projects.apps.d":"Chat application, tennis tournament SNS, TaRO&Company website, and more. Full-stack development across Python, Ruby, Go, Kotlin, Swift, and modern web technologies.",
    // Collaboration
    "news.showAll":"Show All News","news.showLess":"Show Less",
    "talks.showAll":"Show All Talks & Presentations","talks.showLess":"Show Less",
    "awards.showAll":"Show All Awards","awards.showLess":"Show Less",
    "media.showAll":"Show All Media","media.showLess":"Show Less",
    "collab.title":"Let's Work Together","collab.subtitle":"I welcome speaking invitations, research collaborations, and event partnerships.",
    "collab.research":"Research Collaboration","collab.research.d":"I am actively seeking research collaborators in AI, machine learning, and data mining. Let's do something exciting together.",
    "collab.speaking":"Speaking Invitations","collab.speaking.d":"I am actively accepting speaking invitations for conferences, workshops, seminars, and events. Topics include AI/ML research, fashion tech, and industry-academia collaboration.",
    "collab.event":"Event & Conference Co-organizing","collab.event.d":"I am looking for partners to co-organize academic conferences, workshops, tech meetups, and industry events. Whether it's a new conference, a hackathon, or a cross-industry networking event — let's create something exciting together!",
    "collab.mentoring":"Student Mentoring","collab.mentoring.d":"I welcome students who want mentoring in AI/ML research, career development, and more. Whether you're an undergraduate or graduate student — feel free to reach out.",
    "collab.contact":"Feel free to reach out via email or LinkedIn. I look forward to hearing from you!",
    "collab.email":"Contact Me",
    // Footer
    "footer.visitors":"Visitor Map","footer.update":"Last updated: February 2026",
  },
  ja: {
    "nav.about":"概要","nav.publications":"論文","nav.talks":"講演","nav.experience":"職歴","nav.education":"学歴","nav.teaching":"教育","nav.awards":"受賞","nav.media":"メディア","nav.service":"学術活動","nav.projects":"プロジェクト",
    "hero.greeting":"はじめまして、",
    "hero.title":"ZOZO研究所 ディレクター",
    "hero.affil2":"早稲田大学 招聘研究員",
    "hero.affil3":"上智大学 非常勤講師",
    "hero.affil4":"博士（工学）",
    "hero.stat.pubs":"論文数","hero.stat.cit":"被引用数",
    "about.title":"概要",
    "about.p1":"ビジネス目標を実用的なAIソリューションに変換することを専門とし、<strong>推薦システム</strong>、<strong>説明可能なAI</strong>、<strong>コンピュータビジョン</strong>、<strong>大規模言語モデル</strong>、<strong>ビジネスデータ分析と可視化</strong>に関する深い専門知識を持っています。特に、<strong>AIの意思決定を解釈する説明可能AI</strong>や、<strong>答えが1つに定まらない曖昧な問題をAIによってわかりやすくするための分析</strong>（データ &times; AI &times; 曖昧な問題）に興味を持っています。",
    "about.p2":"<a href='https://research.zozo.com/' target='_blank'>ZOZO研究所</a>のディレクターとして、ML R&amp;Dグループを率い、サービス開発や産学連携の研究を推進しています。素敵なメンバーや共同研究者に恵まれ、多数の論文を発表し、多数のメディアに取り上げられています。",
    "about.p3":"教育やメンタリングにも強い情熱を持ち、<a href='https://www.sophia.ac.jp/' target='_blank'>上智大学</a>の非常勤講師および<a href='https://www.waseda.jp/' target='_blank'>早稲田大学</a>の招聘研究員としての活動にも携わっています。",
    "about.interests":"研究分野",
    "pub.title":"論文・学会発表","pub.subtitle":"主要な業績のみ掲載しています。","pub.showAll":"全件を表示","pub.showLess":"折りたたむ","pub.scholarLink":"Google Scholarを見る",
    "pub.filter.all":"すべて","pub.filter.conference":"国際会議","pub.filter.journal":"ジャーナル","pub.filter.workshop":"ワークショップ","pub.filter.preprint":"プレプリント","pub.filter.domestic":"国内",
    "pub.sort":"並び順","pub.sort.year":"新しい順","pub.sort.oldest":"古い順",
    "news.title":"ニュース",
    "news.items":[
      {date:"2026年2月",text:'ホームページを開設しました。様々な分野の研究者やクリエイターの方々とのコラボレーション機会を探すことを目的としています。',isNew:true},
      {date:"2026年2月",text:'<a href="https://zozonext.com/news/20250217_zozoresearch" target="_blank">ICLR 2026</a>に2本の論文が採択されました。',isNew:true},
      {date:"2025年10月",text:'COLM 2025に論文が採択されました。',isNew:false},
      {date:"2025年9月",text:'<a href="https://zozonext.com/news/20251016_zozoresearch" target="_blank">EMNLP 2025</a>に論文が採択されました。',isNew:false},
      {date:"2025年9月",text:'RecSys 2025（Late-Breaking Results）に論文が採択されました。',isNew:false},
      {date:"2025年8月",text:'<a href="https://xtech.nikkei.com/atcl/nxt/mag/rob/18/012600001/00173/?P=3" target="_blank">日経Robotics</a>に研究成果が掲載されました。',isNew:false},
      {date:"2025年6月",text:'ICME 2025（Oral）に論文が採択されました。',isNew:false},
      {date:"2025年5月",text:'千葉工業大学との共同研究が<a href="https://zozonext.com/news/20250526_zozoresearch" target="_blank">IJCAI 2025</a>に採択されました。',isNew:false},
      {date:"2025年2月",text:'<a href="https://zozonext.com/news/20250203_zozoresearch" target="_blank">The Web Conference (WWW) 2025</a>に論文が採択されました。',isNew:false},
      {date:"2025年1月",text:'<a href="https://zozonext.com/news/20250217_zozoresearch" target="_blank">ICLR 2025</a>に論文が採択されました。',isNew:false},
      {date:"2023年8月",text:'<a href="https://www.waseda.jp/top/news/92745" target="_blank">ファッションAI共同研究成果</a>が早稲田大学よりプレスリリースされました。',isNew:false},
      {date:"2023年6月",text:'<a href="https://hotozero.com/knowledge/fis/" target="_blank">「ほとんど0円大学」</a>にて研究紹介記事が掲載されました。',isNew:false},
      {date:"2022年12月",text:'<a href="https://www.nikkei.com/article/DGKKZO66764470S2A211C2TEB000/" target="_blank">日本経済新聞</a>に研究成果が掲載されました。',isNew:false},
      {date:"2022年12月",text:'<a href="https://www.fnn.jp/articles/-/452781" target="_blank">FNN（フジニュースネットワーク）</a>に研究成果が掲載されました。',isNew:false},
      {date:"2022年11月",text:'<a href="https://www.waseda.jp/top/news/85840" target="_blank">Fashion Intelligence System</a>に関する研究成果が早稲田大学よりプレスリリースされました。',isNew:false},
      {date:"2022年5月",text:'執筆を支援した論文が<a href="https://www.jimanet.jp/information/awards/tokubetsu-jissen" target="_blank">経営工学実践賞</a>を受賞しました。「自動車販売店における動画解析技術を用いた顧客行動の可視化と結果の活用」（<a href="https://www.azest.co.jp/news/info/news-355/" target="_blank">AZEST</a>）',isNew:false},
      {date:"2019年3月",text:'早稲田大学大学院 経営システム工学専攻にて専攻賞（優秀学生賞・首席卒業）を受賞しました。',isNew:false},
      {date:"2017年5月",text:'<a href="https://www.jimanet.jp/information/awards/best-presentation-award" target="_blank">日本経営工学会春季大会</a>にてBest Presentation Awardを受賞しました。',isNew:false},
      {date:"2017年4月",text:'Tableau Conference On Tour Tokyo にて、作成したダッシュボードが展示されました。',isNew:false},
      {date:"2016年11月",text:'Tableau Conference 2016 at Austin に参加しました。',isNew:false}
    ],
    "talks.title":"講演・登壇等",
    "talks.invited":"招待講演","talks.award":"受賞者講演","talks.presentation":"登壇","talks.conference":"学会発表","talks.workshop":"ワークショップ","talks.domestic":"国内",
    "talks.confTitle":"学会発表","talks.confDesc":"世界各地のトップ国際会議での口頭・ポスター発表。",
    "talks.wsDesc":"主要なコンピュータビジョン・機械学習カンファレンスでのワークショップ発表。",
    "talks.domesticDesc":"国内学会での発表。JSAI 2023にて研究賞受賞。",
    "exp.title":"職歴",
    "exp.zozo.dir":"ディレクター、デプロイメント部","exp.zozo.dir.d":"ZOZOのサービスに特化したAI技術を研究・開発し、プロダクションシステムにデプロイする部門の立ち上げを担当。",
    "exp.zozo.sm":"マネージャー / リードリサーチサイエンティスト","exp.zozo.sm.d":"10名以上のML研究チームを率いる。WWW、ICLR、IJCAI、EMNLPなどトップ国際会議で論文発表。",
    "exp.zozo.lead":"リードリサーチサイエンティスト","exp.zozo.lead.d":"ファッションインテリジェンス、推薦システム、説明可能AIの応用ML研究を主導。大学・企業との共同研究を推進。",
    "exp.zozo.rs":"リサーチサイエンティスト","exp.zozo.rs.d":"研究活動に加え、Vertex AIによるAutoMLパイプラインの構築や、グループ企業間の連携によるデータ利活用推進プロジェクトなど、事業課題に直結するデータサイエンス・MLエンジニアリング業務に従事。",
    "exp.ucsd":"カリフォルニア大学サンディエゴ校","exp.ucsd.r":"客員研究員、コンピュータサイエンス学部","exp.ucsd.d":"<a href='https://cseweb.ucsd.edu//~jmcauley/' target='_blank'>Julian McAuley研究室</a>にて推薦システム・大規模モデルのファインチューニングなどに関する研究。国際会議で多数の論文を発表。",
    "exp.sophia":"上智大学","exp.sophia.r":"非常勤講師、理工学部","exp.sophia.d":"データ分析、統計モデリング、機械学習、Pythonプログラミングの講義を担当。学生評価：4.8/5.0。",
    "exp.waseda.dsi":"早稲田大学","exp.waseda.dsi.r":"招聘研究員、データサイエンス研究所","exp.waseda.dsi.d":"<a href='https://www.it.mgmt.waseda.ac.jp/index.html' target='_blank'>後藤研究室</a>にて学部生・大学院生の研究指導・メンタリング。",
    "exp.dena":"DeNA Co., Ltd.","exp.dena.r":"ソフトウェアエンジニア","exp.dena.d":"グローバルモバイルゲームのバックエンド開発（Java, GCP）。数百万ユーザー規模のサービスを担当。",
    "exp.pksha":"PKSHA Technology","exp.pksha.r":"インターン","exp.pksha.d":"機械学習エンジニアリングインターン。",
    "exp.startree":"スターツリー株式会社","exp.startree.r":"インターン","exp.startree.d":"PythonやTableauを用いた人事データ分析チームをリード。",
    "exp.azest":"AZEST株式会社","exp.azest.r":"インターン","exp.azest.d":"TableauやPower BIを用いたデータ分析・BI。",
    "exp.toreta":"株式会社トレタ","exp.toreta.r":"インターン","exp.toreta.d":"飲食店テックスタートアップでのフルスタック開発インターン。",
    "edu.title":"学歴",
    "edu.waseda":"早稲田大学","edu.waseda.hs":"早稲田大学高等学院",
    "edu.phd":"博士（工学）創造理工学研究科 経営システム工学専攻","edu.phd.h":["早期卒業","<a href='https://corp.zozo.com/news/20180914-5649/' target='_blank'>ZOZO 社会人ドクター制度</a>（第一号）","指導教員：<a href='https://www.it.mgmt.waseda.ac.jp/index.html' target='_blank'>後藤正幸教授</a>","研究テーマ：機械学習に基づく消費インテリジェンスの獲得とビジネス応用"],
    "edu.ms":"修士（工学）創造理工学研究科 経営システム工学専攻","edu.ms.h":["首席卒業","指導教員：<a href='https://www.it.mgmt.waseda.ac.jp/index.html' target='_blank'>後藤正幸教授</a>","研究テーマ1：ECサイトにおけるアンケートデータを考慮した購買行動分析モデルの提案","研究テーマ2：クレジットとポイントを併用可能な多機能クレジットカードにおける利用履歴データの統合分析モデルの提案","株式会社ZOZO、株式会社小田急電鉄、一般財団法人日本気象協会との共同研究"],
    "edu.bs":"学士（工学）創造理工学部 経営システム工学科",
    "edu.hs":"普通科","edu.hs.h":["<a href='https://www.waseda.jp/school/shs/campus/tennis/' target='_blank'>硬式庭球部</a>（現在、OB会幹事見習い）"],
    "teaching.title":"教育活動",
    "teaching.sophia":"上智大学 — 非常勤講師","teaching.sophia.d":"全学共通科目を担当し、基礎統計とデータ分析、可視化、機械学習手法のビジネスデータ適用、およびそれらに必要なPythonプログラミングをレクチャー。",
    "teaching.sophia.score":"/ 5.0 学生評価平均スコア","teaching.sophia.note":"学生評価スコア：4.8/5.0（最新年度実績）。","teaching.sophia.contact":"授業に関する質問、改善のアドバイス等もお気軽にご連絡ください。",
    "teaching.waseda":"早稲田大学 — 招聘研究員","teaching.waseda.d":"学部生・大学院生の研究指導とメンタリング。",
    "teaching.waseda.streak":"4年連続","teaching.waseda.label":"首席卒業生の指導実績","teaching.waseda.note":"メンタリングした学生が4年連続で首席卒業を達成しています。",
    "teaching.studentMsg":"これまでに授業や研究指導、<a href='https://ut-base.info/circles/122' target='_blank'>HAIT</a>メンタリングなどで関わった学生の皆さんへ — キャリアや研究で悩みがあれば、いつでも気軽に連絡してください。時間が経っていても関係ありません。<strong>いつでもお待ちしています。</strong>",
    "awards.title":"受賞歴",
    "awards.items":[
      {year:"2025年2月",title:"年間最優秀社員賞 準グランプリ — ZOZOグループ",desc:"1,700名以上の社員の中から上位10名に選出。"},
      {year:"2024年12月",title:"Best Paper Award — CIE51",desc:"国際会議 Computers and Industrial Engineering にて受賞。"},
      {year:"2024年11月",title:"最優秀賞 テクノロジー部門 — INTERSECTION 2024（LINEヤフーグループ）",desc:"INTERSECTION 2024（LINEヤフーグループ）のテクノロジー部門で最優秀賞を受賞（27,000名以上の社員の中から3名に選出）。"},
      {year:"2023年10月",title:"Outstanding Paper Award — APIEMS 2023",desc:"国際会議 Asia Pacific Industrial Engineering and Management Systems にて受賞。"},
      {year:"2023年6月",title:"全国大会優秀賞 — 人工知能学会",desc:"ファッション画像検索に関する研究で受賞。"},
      {year:"2023年2月",title:"最優秀賞 — 日科技連データ解析コンペティション",desc:"2023年度データ解析コンペティション JIMA部会にて最優秀賞を受賞。テーマ：商品階層を自動構造化するトピックモデルの提案と小売販売データ分析への適用。"},
      {year:"2022年2月",title:"年間最優秀社員賞 グランプリ — ZOZOグループ",desc:"1,700名以上の中から上位5名に選出。"},
      {year:"2019年3月",title:"最優秀学生賞（首席卒業）— 早稲田大学大学院 経営システム工学専攻",desc:"GPA 3.95で首席卒業。"},
      {year:"2019年2月",title:"技能賞 — 日科技連データ解析コンペティション",desc:"2019年度データ解析コンペティション JIMA部会にて受賞。テーマ：潜在表現モデルに基づくテレビ番組の魅力度要因分析に関する研究。"},
      {year:"2018年5月",title:"優秀賞 — 日本経営工学会 春季学生発表大会",desc:"2018年春季学生発表大会にて受賞。"},
      {year:"2017年5月",title:"優秀学生発表賞 — 日本経営工学会 春季大会",desc:"2017年春季大会にて受賞。"},
      {year:"2017年2月",title:"技能賞 — 日科技連データ解析コンペティション",desc:"2017年度データ解析コンペティション JIMA部会にて受賞。テーマ：ECサイトにおけるアンケートデータを考慮した購買行動分析モデルの提案。"}
    ],
    "media.title":"メディア掲載","media.subtitle":"研究成果が100件以上のメディアで取り上げられています。主な掲載先は以下の通りです。",
    "media.more":"その他、主要テックメディア等100件以上に掲載...",
    "service.title":"学術活動","service.reviewer":"査読者 / プログラム委員","service.details":"詳細","service.note":"複数年の実績を含む",
    "projects.title":"その他活動",
    "projects.tennis":"TaRO's CUP — テニス大会・コミュニティ運営","projects.tennis.d":"テニス大会（TaRO's CUP、第6回以上開催）の主催と活気あるコミュニティの構築。Paradisoやブリヂストンスポーツなどのスポンサーと連携し、あらゆるレベルのプレーヤーが参加できるイベントを運営しています。",
    "projects.nepal":"Nepal Japan Project","projects.nepal.d":"日本とネパール間の国際プロジェクト（2015年、2016年）。2016年はプロジェクトリーダーとして異文化交流・コミュニティ開発を推進。",
    "projects.wedding":"結婚式リアルタイムクイズアプリ","projects.wedding.d":"友人の結婚式用リアルタイムクイズアプリを開発。WebSocketによる同時接続数100名以上に対応。計3回の結婚式で利用。",
    "projects.apps":"個人アプリ・Web開発","projects.apps.d":"チャットアプリ、テニス大会専用SNS、TaRO&Companyホームページなど。Python、Ruby、Go、Kotlin、Swift、モダンWeb技術を用いたフルスタック開発。",
    "news.showAll":"すべてのニュースを表示","news.showLess":"折りたたむ",
    "talks.showAll":"すべての講演・発表を表示","talks.showLess":"折りたたむ",
    "awards.showAll":"すべての受賞歴を表示","awards.showLess":"折りたたむ",
    "media.showAll":"すべてのメディア掲載を表示","media.showLess":"折りたたむ",
    "collab.title":"講演・共同研究のご依頼","collab.subtitle":"講演依頼、共同研究、イベント共催のご相談を歓迎しています。",
    "collab.research":"共同研究","collab.research.d":"AI・機械学習・データマイニング領域での共同研究者を積極的に募集しています。一緒に面白いことをしましょう。",
    "collab.speaking":"講演依頼","collab.speaking.d":"カンファレンス、ワークショップ、セミナー、イベントでの講演依頼を積極的に受け付けています。AI/ML研究、ファッションテック、産学連携などのテーマで講演可能です。",
    "collab.event":"イベント・学会の共催","collab.event.d":"学会やワークショップ、テック勉強会、業界イベントを一緒に企画・運営してくれる方を募集しています。新しいカンファレンスの立ち上げ、ハッカソン、異業種交流イベントなど、一緒に面白いことをやりましょう！",
    "collab.mentoring":"メンタリング","collab.mentoring.d":"AI・機械学習の研究やキャリアなどについてメンタリングを希望する学生を歓迎しています。学部生・大学院生の方、お気軽にご連絡ください。",
    "collab.contact":"お気軽にメールまたはLinkedInからご連絡ください。お待ちしております！",
    "collab.email":"お問い合わせ",
    "footer.visitors":"訪問者マップ","footer.update":"最終更新：2026年2月",
  }
};

// ===== Talks Data =====
const TALKS = [
  { year:"Sep 2025", yearJa:"2025年9月", type:"invited", title:"WebDB Summer Workshop 2025", titleJa:"WebDB夏のワークショップ2025", desc:"\"Data Science for Interpreting Ambiguous Fashion\" — Hamamatsu, Japan", descJa:"「曖昧なファッションを解釈するためのデータサイエンス」— 浜松", link:"https://shoji-lab.github.io/%E7%99%BA%E8%A1%A8/2025/09/18/WebDB_present.html", image:"pics/presentation_photo.jpg" },
  { year:"Jun 2025", yearJa:"2025年6月", type:"invited", title:"Sorbonne University IMCDS — Guest Lecture in Tokyo (Organizer & Speaker)", titleJa:"ソルボンヌ大学 IMCDS — 東京招待講演（主催・講演）", desc:"Organized and presented a research lecture to visiting Sorbonne IMCDS Master's students on AI applications in fashion.", descJa:"ソルボンヌ大学IMCDSの来日学生に対し、ファッションにおけるAI応用に関する研究講演を主催・実施。", link:"https://www.linkedin.com/posts/master-imcds_imcds-artificialintelligence-machinelearning-activity-7336640518459731968-Cb20", image:"pics/sorbonne_lecture.jpg" },
  { year:"2024", yearJa:"2024年", type:"award", title:"INTERSECTION 2024", titleJa:"INTERSECTION 2024", desc:"\"Fashion Intelligence System: Fashion-Specific Ambiguous Expression Interpretation\" — Presented at INTERSECTION 2024 (LINE Yahoo! Group).", descJa:"「Fashion Intelligence System: ファッション特有の曖昧な表現解釈」— INTERSECTION 2024（LINEヤフーグループ）にて発表。", link:"https://www.youtube.com/watch?v=KPPt2ULldfg", image:"pics/hero_background.jpg" },
  { year:"Dec 2023", yearJa:"2023年12月", type:"presentation", title:"CCSE 2023 — Fashion Expression Interpretation", titleJa:"CCSE 2023 — ファッション表現解釈", desc:"\"A System for Interpreting Fashion-Specific Ambiguous Expressions Using Vision-Language Models\" — Conference on Computer Science for Enterprise.", descJa:"「画像言語モデルを用いたファッション特有の曖昧な表現を解釈するシステム」— CCSE 2023にて発表。", link:"https://ccse.jp/2023/speakers/", image:null },
  { year:"Mar 2023", yearJa:"2023年3月", type:"invited", title:"AZEST Spark Labs — Fashion Intelligence System", titleJa:"AZEST Spark Labs — Fashion Intelligence System", desc:"\"Fashion Intelligence System\" — Presented AI-driven fashion interpretation technology to AZEST employees and industry professionals.", descJa:"「Fashion Intelligence System」— AZEST社員・業界関係者にAIファッション解釈技術を講演。", link:"https://www.azest.co.jp/sparklabs/lab-868/", image:"pics/azest_lab_2.png" },
  { year:"Dec 2021", yearJa:"2021年12月", type:"presentation", title:"CCSE 2021 — Presentation & Panel Discussion", titleJa:"CCSE 2021 — 発表・パネルディスカッション", desc:"Regular presentation: \"Discovery of Potential Customers Using External Domain Data.\" Panel discussion: \"Research Planning in Corporate Settings.\" — Conference on Computer Science for Enterprise.", descJa:"【発表】外部ドメインデータを活用した潜在顧客発見に向けた取り組み。【パネル】企業の研究における研究計画の作り方。— CCSE 2021。", link:"https://ccse.jp/2021/", image:null },
  { year:"Oct 2019", yearJa:"2019年10月", type:"presentation", title:"DeNA Tech Talk — Tennis SNS for 400 Users", titleJa:"DeNA全社テックトーク — テニス大会SNSの開発", desc:"\"How a New Graduate Engineer Developed a Tennis Tournament SNS Used by 400 People in One Month\" — Company-wide tech talk at DeNA.", descJa:"「新卒未経験エンジニアが1ヶ月で開発したテニス大会用のSNSを400人に使ってもらった話」— DeNA全社テックトーク。", link:null, image:"pics/dena_techtalk.jpg" },
  { year:"Sep 2019", yearJa:"2019年9月", type:"invited", title:"AZEST Inc. Tech Talk", titleJa:"AZEST株式会社 テックトーク", desc:"Technical presentation on machine learning engineering.", descJa:"機械学習エンジニアリングに関する技術講演。", link:null, image:"pics/azest_lab_1.jpeg" },
];

// ===== Media Data =====
const MEDIA = [
  // 2026
  { source:"ZOZO NEXT", title:"Two papers accepted at ICLR 2026", titleJa:"ICLR 2026に2本の論文が採択", url:"https://zozonext.com/news/20260217_zozoresearch", date:"Feb 2026" },
  // 2025
  { source:"ZOZO NEXT", title:"ZOZO Research paper accepted at EMNLP 2025", titleJa:"ZOZO研究所の論文がEMNLP 2025に採択", url:"https://zozonext.com/news/20251016_zozoresearch", date:"Oct 2025" },
  { source:"日経Robotics", title:"Easier addition/removal of tasks in neural networks — new regularization by Tokyo Science Univ. & ZOZO", titleJa:"ニューラルネットへのタスクの追加・削除が容易に、東京科学大やZOZOの新正則化技術", url:"https://xtech.nikkei.com/atcl/nxt/mag/rob/18/012600001/00173/?P=3", date:"Aug 2025" },
  { source:"ZOZO NEXT", title:"Joint research with CIT accepted at IJCAI 2025", titleJa:"千葉工業大学との共同研究がIJCAI 2025に採択", url:"https://zozonext.com/news/20250526_zozoresearch", date:"May 2025" },
  { source:"日本ネット経済新聞", title:"ZOZO Research presents new AI methods — joint research with CIT accepted at IJCAI 2025", titleJa:"ZOZO研究所、AI分野で新手法発表 千葉工大との共同研究が「IJCAI 2025」で論文採択", url:"https://netkeizai.com/articles/detail/14647", date:"May 2025" },
  { source:"ZOZO NEXT", title:"ZOZO Research paper accepted at The Web Conference 2025", titleJa:"ZOZO研究所の論文がThe Web Conference 2025に採択", url:"https://zozonext.com/news/20250203_zozoresearch", date:"Feb 2025" },
  { source:"ZOZO NEXT", title:"Two papers accepted at ICLR 2025", titleJa:"ICLR 2025に2本の論文が採択", url:"https://zozonext.com/news/20250217_zozoresearch", date:"Feb 2025" },
  // 2024
  { source:"ZOZO NEXT", title:"ZOZO Research paper accepted at ICLR 2024", titleJa:"ZOZO研究所の論文がICLR 2024に採択", url:"https://zozonext.com/news/20240214_zozoresearch", date:"Feb 2024" },
  // 2023
  { source:"ZOZO NEXT", title:"AI interpreting individual fashion item characteristics", titleJa:"個々のファッションアイテムの特徴に着目した曖昧なファッション表現を自動解釈するAI技術を開発", url:"https://zozonext.com/news/20230808_zozoresearch", date:"Aug 2023" },
  { source:"AISmiley", title:"Waseda & ZOZO Research develop AI to interpret ambiguous fashion at item level", titleJa:"早大とZOZO研究所、曖昧なファッションの表現をAIで解釈する技術を開発。アイテムごとで質問の回答が可能に", url:"https://aismiley.co.jp/ai_news/waseda-zozo-partial-visual-semantic-embedding/", date:"Aug 2023" },
  { source:"Waseda Univ.", title:"AI That Interprets Fashion Items — Waseda × ZOZO Research", titleJa:"ファッションアイテムまで解釈するAI — 早稲田大学×ZOZO研究所", url:"https://www.waseda.jp/top/news/92745", date:"Aug 2023" },
  // 2022
  { source:"日本経済新聞", title:"AI provides fashion advice for ambiguous questions — ZOZO & Waseda", titleJa:"「カジュアルな装いとは？」AIがファッション助言　ZOZO系・早大　曖昧な質問も対応", url:"https://www.nikkei.com/article/DGKKZO66764470S2A211C2TEB000/", date:"Dec 2022" },
  { source:"日経クロステック", title:"Waseda & ZOZO Research develop new AI for fashion analysis and advice", titleJa:"早大とZOZO研、AIがファッションを解析してアドバイスする新技術", url:"https://xtech.nikkei.com/atcl/nxt/news/18/14221/", date:"Dec 2022" },
  { source:"AISmiley", title:"ZOZO NEXT & Waseda develop AI to interpret ambiguous fashion expressions", titleJa:"ZOZO NEXTと早大大学院 曖昧なファッションの表現をAIが自動で解釈する技術を開発", url:"https://aismiley.co.jp/ai_news/zozo-waseda-fashionintelligencesystem/", date:"Dec 2022" },
  { source:"FNN", title:"AI that understands ambiguous fashion expressions", titleJa:"曖昧なファッション表現を理解するAI", url:"https://www.fnn.jp/articles/-/452781", date:"Dec 2022" },
  { source:"大学ジャーナルオンライン", title:"AI proposes outfits from ambiguous fashion images — Waseda & ZOZO Research", titleJa:"曖昧なファッションのイメージから服装を提案するAI 早稲田大学・ZOZO研究所が開発", url:"https://univ-journal.jp/197343/", date:"Nov 2022" },
  { source:"ネットショップ担当者フォーラム", title:"ZOZO develops AI to interpret ambiguous fashion expressions", titleJa:"ZOZO、曖昧なファッションの表現をAIが自動で解釈する技術を開発", url:"https://netshop.impress.co.jp/node/10377", date:"Nov 2022" },
  { source:"Digital Shift Times", title:"ZOZO & Waseda develop AI to interpret ambiguous fashion expressions", titleJa:"ZOZOと早稲田大学、AIが曖昧なファッションの表現を自動で解釈する技術を開発", url:"https://digital-shift.jp/flash_news/FN221124_1", date:"Nov 2022" },
  { source:"AI Market", title:"ZOZO & Waseda co-develop Fashion Intelligence System", titleJa:"ZOZO、曖昧なファッションの表現についてAIが自動で解釈する「Fashion Intelligence System」を早大と共同開発", url:"https://ai-market.jp/news/zozo-wasedauniversity-fashionintelligencesystem/", date:"Nov 2022" },
  { source:"Waseda Univ.", title:"AI interprets ambiguous fashion expressions — Waseda × ZOZO Research", titleJa:"曖昧なファッションの表現をAIで解釈", url:"https://www.waseda.jp/top/news/85840", date:"Nov 2022" },
  { source:"PR Times", title:"AI technology to automatically interpret ambiguous fashion expressions", titleJa:"曖昧なファッションの表現をAIが自動で解釈する技術を開発", url:"https://prtimes.jp/main/html/rd/p/000000100.000096287.html", date:"Nov 2022" },
  // Interviews & Blog
  { source:"ほとゼロ", title:"Interview: Understanding Fashion Intelligence System — with Prof. Goto & Shimizu", titleJa:"インタビュー：曖昧なファッション表現に対するAIの回答 — 後藤教授・清水良太郎", url:"https://hotozero.com/knowledge/fis/", date:"Jun 2023", category:"interview" },
  { source:"ZOZO Tech Note", title:"Interview: Research Scientist at ZOZO Research", titleJa:"インタビュー：ZOZO研究所の研究者としての歩み", url:"https://technote.zozo.com/n/n8d261b1d4785", date:"2023", category:"interview" },
  { source:"ZOZO Tech Blog", title:"Tech blog on Wantedly — ZOZO Engineering", titleJa:"ZOZOテクノロジーズ テックブログ", url:"https://www.wantedly.com/companies/zozo-tech/post_articles/336169", date:"Sep 2021", category:"blog" },
];
